### ISSUE TITLE
奇舞学院Javascript——如何写好原生js

### ISSUE THREAD

**Issue by jscgq** [jscgq/Blog#15]
### 版本1 (初学者）
```js
const list = document.querySelector('#user-list');
const items = document.querySelectorAll('#user-list > li');

list.addEventListener('click', function(e){
    if(e.target.tagName === 'LI'){
        let item = e.target;
        items.forEach(function(item){
            item.style.background = 'inherit';
            item.style.color = 'inherit';
        });
        item.style.background = 'black';
        item.style.color = 'white';
        console.log(item.innerHTML);
    }
});
```
优点： 事件委托
缺点：直接操作dom元素的样式， 职责没有划分清楚， JavaScript应该尽量操作状态。
### 版本2 （中规中矩）
```js
const list = document.querySelector('#user-list');
const items = list.querySelectorAll('li');
function addClass(el, cls){
  removeClass(el, cls);
  el.className += (' ' + cls).trim();
}
function removeClass(el, cls){
  let pattern = new RegExp('(?:^|\s+)' + cls + '(?:\s+|$)', 'g');
  el.className = el.className.replace(pattern, ' ').trim();
}
list.addEventListener('click', function(e){
    items.forEach(function(item){
        removeClass(item, 'active');
    });
    if(e.target.tagName === 'LI'){
        let item = e.target;
        addClass(item, 'active');
        console.log(item.innerHTML);
    }
});
```
优点： 添加active的状态，具体样式交给css。
扩展： JavaScript代码可以写的更少，借助原生radio。
### 版本3
```html
<ul id="user-list">
    <li><input name="items" id="item0" type="radio" value="张三"/><label for="item0">张三</label></li>
    <li><input name="items" id="item1" type="radio" value="李四"/><label for="item1">李四</label></li>
    <li><input name="items" id="item2" type="radio" value="王五"/><label for="item2">王五</label></li>
    <li><input name="items" id="item3" type="radio" value="赵六"/><label for="item3">赵六</label></li>
</ul>
```

```css
body{
    background-color: white;
    font-size: 24px;
}

#user-list{
    line-height: 1.5em;
}

#user-list input{
    display: none;
}

#user-list label{
    display: block;
}

.#user-list > li:hover{
    background-color: rgba(0,0,0,0.3);
}

#user-list input:checked+label{
    background-color: black;
    color: white;
}
```

```js
const list = document.querySelector('#user-list');

list.addEventListener('click', function(e){
    if(e.target.tagName === 'INPUT'){
        let checkedItem = list.querySelector('input:checked');
        console.log(checkedItem.value);
    }
});
```
优点： 扩展性强，职责划分明确。

## Q2: API设计（红绿灯）

```html
    <ul class="stop" id = "traffic">
        <li></li>
        <li></li>
        <li></li>
    </ul>
```

```css
        li {
            list-style: none;
            display: block;
            width: 20px;
            height: 20px;
            background: #aaa;
            border-radius: 10px;
            margin-bottom: 10px;
        }
        ul.stop>li:first-child {
            background: #ff0000;
        }
        ul.run>li:last-child {
            background: #00ff00;
        }
        ul.wait>li:nth-child(2) {
            background: #ffff00;
        }
```
### 版本1（只考虑实现）
```js
const traffic = document.getElementById('traffic');
(function reset(){
  traffic.className = 'wait';
  setTimeout(function(){
      traffic.className = 'stop';
      setTimeout(function(){
        traffic.className = 'pass';
        setTimeout(reset, 2000)
      }, 2000)
  }, 2000);
})();
```
缺点：过程耦合，回调地狱
### 版本2（新手）
```js
const traffic = document.getElementById('traffic');
var stateList = ['wait', 'stop', 'pass'];
var currentStateIndex = 0;
setInterval(function(){
  var state = stateList[currentStateIndex];
  traffic.className = state;
  currentStateIndex = (currentStateIndex + 1) % stateList.length;
}, 2000);
```
缺点：封装性不好
### 版本3 （中规中矩）
```js
const traffic = document.getElementById('traffic');

function start(traffic, stateList){
  var currentStateIndex = 0;
  setInterval(function(){
    var state = stateList[currentStateIndex];
    traffic.className = state;
    currentStateIndex = (currentStateIndex + 1) % stateList.length;
  }, 2000);
}
start(traffic, ['wait', 'stop', 'pass']);
```
缺点：可复用性差
优点： 有意识地设计了API，暴露和封装了所需的参数。
### 版本4（过程抽象）
```js
const traffic = document.getElementById('traffic');
function poll(...fnList){
  let stateIndex = 0;
  return function(...args){
    let fn = fnList[stateIndex++ % fnList.length];
    return fn.apply(this, args);
  }
}
function setState(state){
  traffic.className = state;
}
let trafficStatePoll = poll(setState.bind(null, 'wait'),
                            setState.bind(null, 'stop'),
                            setState.bind(null, 'pass'));
setInterval(trafficStatePoll, 2000);
```
抽象抽出了一个poll函数，一个通用的轮流执行函数，可以用来执行toggle、循环动画等等。
缺点：需求变动，要求红黄绿时间为3，2，1s。只有版本1可以
### 版本5（借用promise解决版本1的缺点）
```js
const traffic = document.getElementById('traffic');
function wait(time){
  return new Promise(resolve => setTimeout(resolve, time));
}
function setState(state){
  traffic.className = state;
}
function reset(){
  Promise.resolve()
    .then(setState.bind(null, 'wait'))
    .then(wait.bind(null, 1000))
    .then(setState.bind(null, 'stop'))
    .then(wait.bind(null, 2000))
    .then(setState.bind(null, 'pass'))
    .then(wait.bind(null, 3000))
    .then(reset);
}
reset();
```
也可以用async和await
```js
const traffic = document.getElementById('traffic');
function wait(time){
  return new Promise(resolve => setTimeout(resolve, time));
}
function setState(state){
  traffic.className = state;
}
async function reset(){
  //noprotect
  while(true){
    setState('wait');
    await wait(1000);
    setState('stop');
    await wait(2000);
    setState('pass');
    await wait(3000);
  }
}
reset();
```
### 版本6（class）
```js
const trafficEl = document.getElementById('traffic');
function TrafficProtocol(el, reset){
  this.subject = el;
  this.autoReset = reset;
  this.stateList = [];
}
TrafficProtocol.prototype.putState = function(fn){
  this.stateList.push(fn);
}
TrafficProtocol.prototype.reset = function(){
  let subject = this.subject;
  this.statePromise = Promise.resolve();
  this.stateList.forEach((stateFn) => {
    this.statePromise = this.statePromise.then(()=>{
      return new Promise(resolve => {
        stateFn(subject, resolve);
      });
    });
  });
  if(this.autoReset){
    this.statePromise.then(this.reset.bind(this));
  }
}
TrafficProtocol.prototype.start = function(){
  this.reset();
}
var traffic = new TrafficProtocol(trafficEl, true);
traffic.putState(function(subject, next){
  subject.className = 'wait';
  setTimeout(next, 1000);
});
traffic.putState(function(subject, next){
  subject.className = 'stop';
  setTimeout(next, 2000);
});
traffic.putState(function(subject, next){
  subject.className = 'pass';
  setTimeout(next, 3000);
});
traffic.start();
```
优点：面向对象、函数式编程
缺点：可能过度设计、实现难度比较大
## Q3: JavaScript的效率
>给定一个很大的数组，数组里面有许多整数，用 JavaScript 实现一个函数，要求：
>将数组中之和为 10 的每一对数配对并找出，返回这些数配对后的数组。
>例如：[11, 3, 8, 9, 7, -1, 1, 2, 4…]
>得到：[[11,-1],[3,7],[8,2],[9,1]…]
